# Generated by Django 5.1.2 on 2025-07-04 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UpstoxFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('funds', models.DecimalField(decimal_places=2, max_digits=15)),
                ('percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('investable_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
            ],
        ),
    ]
