# Generated by Django 5.1.2 on 2025-07-05 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copy_trading', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentCSV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='csv_files/')),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
