# Generated by Django 5.1.2 on 2025-07-07 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copy_trading', '0003_fundinstrument_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundinstrument',
            name='token',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
