# Generated by Django 5.1.2 on 2025-08-05 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copy_trading', '0004_alter_fundinstrument_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundinstrument',
            name='sandbox_token',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
