# Generated by Django 5.2.4 on 2025-10-27 04:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copy_trading', '0005_fundinstrument_sandbox_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ZerodhaInstrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('funds', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('invest_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('percentage', models.DecimalField(decimal_places=2, help_text='Percentage of total funds to be invested', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('investable_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('call_lot', models.PositiveIntegerField(default=0)),
                ('put_lot', models.PositiveIntegerField(default=0)),
                ('token', models.CharField(blank=True, max_length=500, null=True, unique=True)),
                ('sandbox_token', models.CharField(blank=True, max_length=500, null=True, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zerodha_instruments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
