# Generated by Django 5.2.4 on 2025-10-27 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('copy_trading', '0006_zerodhainstrument'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zerodhainstrument',
            old_name='sandbox_token',
            new_name='api_key',
        ),
    ]
