# Generated by Django 5.2.4 on 2025-10-28 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copy_trading', '0007_rename_sandbox_token_zerodhainstrument_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundinstrument',
            name='api_key',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='fundinstrument',
            name='zerodha_token',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
