# Generated by Django 5.2.4 on 2025-10-31 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copy_trading', '0008_fundinstrument_api_key_fundinstrument_zerodha_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundinstrument',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
